### ISSUE TITLE
"no-quoteless-attributes" & arguments?

### ISSUE THREAD

**Issue by lougreenwood** [ember-template-lint/ember-template-lint#1112]
The `no-quoteless-attributes` rule also triggers when using un-quoted *arguments*.

<img width="746" alt="Screenshot 2019-12-19 at 15 30 41" src="https://user-images.githubusercontent.com/12051736/74440349-c1e69900-4e65-11ea-95d9-f73666669546.png"> 

This is confusing, because when I saw the rule for the first time, I didn't really know if this was also really valid for `arguments` or if it was actually some bug in the rule which caught `arguments` when it should only apply to `attributes`.

Perhaps the rule name & warning should be clarified to suggest that this rule is for both attributes and arguments?

Alternatively, perhaps a separate `no-quoteless-arguments` rule is needed?

**Comment by rwjblue** [comment]
Hmm, I definitely see what you mean here. I'm happy to have another rule that is _basically_ the same as `no-unquoted-attributes` for the sheer fact that it will be clearer to folks (even though _in the AST_ there is no differentiation between attributes and arguments).

It would also be nice because the suggested fix for `no-quoteless-arguments` would likely be to wrap the value in mustaches (e.g. `<Foo @bar=derp />` -> `<Foo @bar={{derp}} />`).

**Comment by lifeart** [comment]
seems related: https://github.com/ember-template-lint/ember-template-lint/pull/927
I can split it to smaller PR's if I able to figure out rule names and scope for each rule :)

**Comment by Turbo87** [comment]
> It would also be nice because the suggested fix for no-quoteless-arguments would likely be to wrap the value in mustaches (e.g. <Foo @bar=derp /> -> <Foo @bar={{derp}} />).

I'm not sure if that's correct. In some cases wrapping it in quotes might be correct. Since this potentially changes the code logic I'm a bit worried about adding automatic fixing to this rule 🤔

**Comment by bar** [comment]
@Turbo87 I'm sorry but I didn't get that :)
