### ISSUE TITLE
Binding computed properties to tabindex should (probably) be allowed?

### ISSUE THREAD

**Issue by linearza** [ember-template-lint/ember-template-lint#1491]
Hi!

For context please see my comment on the original MR here: https://github.com/ember-template-lint/ember-template-lint/pull/633#issuecomment-681698068

To summarise, currently `tabindex={{prop}}` isnt allowed by the `no-positive-tabindex` rule. While this is fine in most cases as these values dont usually change based on interaction, it does become problematic in cases where you have a nested reusable component which requires this value to be passed in, as is our case.

Based on that I think the rule should allow dynamic bindings

**Comment by MelSumner** [comment]
@linearza thanks for filing this issue! I wonder...is it possible for you to do a [conditional](https://guides.emberjs.com/release/components/conditional-content/) here? I'll look at the rule as soon as I can to see exactly what it expects, but I would expect it to support a conditional (because then I think we could still make sure the values were `-1` and `0`).

**Comment by rwjblue** [comment]
Yes, the rule does allow for usage of an inline if as long as the true/false values are statically either `0` or `-1`.

**Comment by linearza** [comment]
So perhaps Im getting the syntax wrong here, but the syntax we had originally was: `tabindex={{if @tabindex "0"}}` I also quickly tried `tabindex={{if @tabindex @tabindex "0"}}` - neither are allowed it seems

**Comment by linearza** [comment]
I think we can go with `tabindex={{if (eq @tabindex "-1") "-1" "0"}}` in our case - seems a bit explicit, but does the job and passes the rule.

Will close this issue for now.

Thanks
