### ISSUE TITLE
Why is a11y preset is not listed in README

### ISSUE THREAD

**Issue by brkn** [ember-template-lint/ember-template-lint#1677]
Why is `a11y` preset not listed in README?
Is there a reason for this, or can I safely add this to my config?

**Comment by rwjblue** [comment]
@brkn - We should definitely ensure that all of the configurations that we ship are mentioned in the README. Using A11Y config is definitely something that you can do in your application, but note that since it's goal is to include **all** A11Y related rules it does not follow the same SemVer rules as other presets. See our [versioning](https://github.com/ember-template-lint/ember-template-lint/blob/master/dev/versioning.md#exemptions) doc for more details.

**Comment by rwjblue** [comment]
Would love a PR updating the documentation here!

**Comment by MelSumner** [comment]
@brkn it depends on what you mean by safely- it's exempt from the versioning policy for specific reasons- see  https://github.com/ember-template-lint/ember-template-lint/blob/master/dev/versioning.md#exemptions
