### ISSUE TITLE
Remove `moduleId` and `moduleName` references for 3.0.0

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#1781]
`moduleId` / `moduleName` were deprecated in #1760 (released in 2.19.0). We should remove all references to `moduleId` / `moduleName` in the `next` branch (fully closing #1346).

**Comment by scalvert** [comment]
The pending feature depends on a reference to `moduleId`, so I'll leave that in for now until that feature is removed.

**Comment by scalvert** [comment]
Unsure if it's worth tying this to 3.0, since the pending feature isn't going to be removed for a while, and these features are linked (pending requires moduleId, as you know). Do you think it's worth doing this now?

I can imagine removing it from the verify API and the results, but only using it for pending. It will take a bit of time to ensure we don't break either. If we wait, we can nuke it all in one fell swoop.

WDYT?

**Comment by scalvert** [comment]
Discussed offline with @rwjblue. We decided to scope this to

- Removing `moduleId` from the `log` function and resulting output from results
- Removing these properties from the rule tester infrastructure

For remaining references to `moduleId`/`moduleName`, we're going to wait to remove them when removing the deprecated `pending` feature for v4

**Comment by scalvert** [comment]
Outstanding references to `moduleId` will be removed with the pending feature for v4.
