### ISSUE TITLE
[todos] Auto-delete stale todo file if there are no other todos in that file

### ISSUE THREAD

**Issue by scalvert** [ember-template-lint/ember-template-lint#1878]
The current functionality detects if a todo file is stale, and pushes an error into the results instructing users to re-run ember-template-lint with the `--fix` option. 

Our intent with forcing you to explicitly 'fix' the stale todo file was that for destructive operations like this, it's safer for us to expect the user to take explicit action vs. attempting to infer the behavior. While we still believe this is the right thing to do, as it prevents issues such as 

- ember-template-lint runs in an IDE that auto-saves (via unsafe ember language server, for instance)
- user edits a file, line numbers change, todos become stale
- _if we're auto-deleting_, the stale todo file is deleted
- user undos previous changes
- todo file is still deleted

we still believe there could be some optimizations made WRT improving DX. This issue tracks exploration of that work. Primarily, we want to explore if it's possible to delete stale todos without requiring the user to take action, or whether this will add too much friction to the entire process.

**Comment by MelSumner** [comment]
Capturing offline conversation: 

So I have been thinking through this and I believe our decision for preventing automatic destructive behavior still stands. 

I think that auto-deleting stale todos might be too much cognitive overload for something that could otherwise be muscle memory when devs get used to it. 

"sometimes it will auto-delete and some times it doesn't" 
vs 
"remember to run --fix after you fix something"

**Comment by MelSumner** [comment]
Since experimenting with this feature, we have received user feedback that they do not want any automatic removal of todos. Closing issue.
