### ISSUE TITLE
Consider adding lint-staged to default

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1902]
Recently I was working on a project that is adding [lint-staged](https://github.com/okonet/lint-staged) to the template linting workflow. It made me wonder if we should consider adding this to the default for the addon. What do you think?

**Comment by rwjblue** [comment]
I don't particularly like the idea of linting only staged files due to the common pitfalls around changing linting rules but not also fixing the new failures (the failures would *not* be in a staged file, so it may not get linted if you are using lint-staged primarily). Some folks implement lint-staged as a precommit hook (e.g. with husky or other tool to provide easy integration with git hooks), but often times this just teaches developers to run `git commit -n` to avoid the hooks and you loose the benefit.

Either way, this would have to be an ember-cli related RFC scenario (not something in the ember-template-lint space) so I'm going to go ahead and close here.

**Comment by MelSumner** [comment]
I definitely wouldn't want it to replace the default linting command but rather be an extra option. Thanks for the feedback!
