### ISSUE TITLE
Colocate all rule files?

### ISSUE THREAD

**Issue by bertdeblock** [ember-template-lint/ember-template-lint#2198]
I don't know if this has been discussed before or if this is technically feasible, but at first glance, I think it would be nice if a rule's files (implementation + tests + docs) would be colocated in a single folder.

```
-- rules
  -- no-model-argument-in-route-templates
    -- docs.md
    -- rule.js
    -- test.js
```

I think it would make authoring rules and navigating the codebase slightly nicer.

What do you guys think?

**Comment by bertdeblock** [comment]
Possible downsides:

- Rule docs would be separated from the other docs (migration docs, todo docs, ...)
- Can we still require all rules at once like [how we do it now](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/index.js)?

**Comment by lifeart** [comment]
@bertdeblock it may break existing links to documentation we have https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/utils/diagnostic.ts#L73

**Comment by bmish** [comment]
It's a neat idea, but unfortunately, I'm not in favor of it because:

1. It would break all rule documentation links provided by existing installations of ember-template-lint and shared throughout the ecosystem. This kind of churn is unacceptable IMO.
2. Nearly all ESLint plugins follow the rules, tests, docs folder structure, and I think we should be matching ESLint conventions as closely as possible.
3. While I agree colocation has some convenience benefits when actively developing a rule, to me this is outweighed by the downsides it has regarding making it less straightforward for our tooling/configuration to operate on different kinds of files, and breaking the assumption that all tests live in one place, all docs live in one place, etc.

What I recommend instead is convenience scripts in package.json:
* `yarn dev [rule-name]`: new script, opens up all files for the desired rule in your code editor. eslint-plugin-unicorn has a [script that does this](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/2e22382a7581ab8ebdf0c12195d11817b5818d66/scripts/create-rule.mjs#L165).
* `yarn new:rule` - existing script, update it to open up all the files for the new rule
