### ISSUE TITLE
New rule: `no-array-prototype-extensions`

### ISSUE THREAD

**Issue by smilland** [ember-template-lint/ember-template-lint#2450]
We are moving away from array prototype extensions. Similar like new rule [no-array-prototype-extensions](https://github.com/ember-cli/eslint-plugin-ember/pull/1461) in [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember). We should create a rule to disallow `.firstObject.` `.lastObject.` access.

**Comment by smilland** [comment]
For name: would it be better if we do `no-array-prototype-extension-properties` or be more specific as `no-firstobject-lastobject`?

**Comment by bmish** [comment]
I would like to make sure `array` is in the name. Similar to how [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn#rules) also has a lot of `no-array-*` rules. 

* `no-array-prototype-extensions`, this is my slight preference as it makes it clear it's related to the eslint-plugin-ember version of the rule, makes the intent clear rather than just referring to the properties, has room for expansion if we discover something else to catch beyond just those two properties
* `no-array-firstobject-lastobject`, this is also good but maybe overy-specific

**Comment by smilland** [comment]
`no-array-prototype-extensions` for consistency 👍
