### ISSUE TITLE
[Todo feature] Missing newline when generating `remove` lines in `.lint-todo`

### ISSUE THREAD

**Issue by Windvis** [ember-template-lint/ember-template-lint#2482]
After fixing some linting errors that were previously added to the `.lint-todo` file I ran `npm run lint:hbs` to check if I didn't create any new issues. To my confusion a totally unrelated linting error was shown.

Upon inspection of the `.lint-todo` file, I noticed that new `remove` prefixed lines were added but the first one didn't start on a new line and instead started right at the end of the previous `add` line which made the error appear again in the linting output:

```
... other lines that were added previously
add|ember-template-lint|simple-unless|134|8|134|8|02b279bc993a1ee6632c7e6edf341a2aabc519cb|1649980800000|||app/templates/subsidy/applications/edit/step/edit.hbsremove|ember-template-lint|no-action|51|20|51|20|9d210688d82ca2d429ebdcf858994aa0c1da7828|1649980800000|||app/components/shared/persoon/create-persoon.hbs
... other remove lines
```

Manually moving it to a new line makes it work as expected again.

**Comment by angelayanpan** [comment]
![Screen Shot 2022-06-06 at 3 08 02 PM](https://user-images.githubusercontent.com/2455168/172231376-9af7b21b-d4fc-4e3c-a321-af43f2eacec5.png)

**Comment by angelayanpan** [comment]
also running into this bug

**Comment by angelayanpan** [comment]
I saw this behavior after running: `yarn ember-template-lint . --update-todo`

**Comment by Techn1x** [comment]
This could have been fixed already, but should be fixed _for sure_ in `@lint-todo/utils` 13.1.1
https://github.com/lint-todo/utils/pull/578

I've posted a PR for ember-template-lint to update to it
https://github.com/ember-template-lint/ember-template-lint/pull/2955

**Comment by Techn1x** [comment]
The issue was that certain commands were not applying a newline to the end of the file, depending on what version you were using. Then, after that, if you did an append operation (like update-todo) it would be joined to the line prior since there was no newline.

13.1.1 should have fixed all the remaining commands to apply a newline after their output - but if you have a `.lint-todo` file from a prior version it still might not have the newline at the end until you run your next command, so it's possible you'll end up with one more doubled todo operation line, _then_ it'll be resolved.

**Comment by bmish** [comment]
Should be fixed by https://github.com/ember-template-lint/ember-template-lint/pull/2955.
