### ISSUE TITLE
embedded templates not working properly 

### ISSUE THREAD

**Issue by vagarii** [ember-template-lint/ember-template-lint#2660]
Hi there, I tried using ember-template-lint for linting embedded templates(inside .js not .hbs) but it seems like it didn't work. Wondering if it's ignore js file so I did add `--no-ignore-pattern` but still no luck. The output is just `done in xxx second` but I am pretty sure the files I am working on have lint issue. Can you guys help me with this, does the `embedded templates` unstable since it's quite new feature?

Here is my current version: 
- "ember-template-lint": "^4.15.1"
- "node": "14.17.5"

cc: @tstewart15

**Comment by tstewart15** [comment]
Hi team, to provide further details, the support for linting embedded hbs in .js files was added in #2483 by @rwjblue and @ventuno 

We tried to pull this in as we're eager to get template linting in our GlimmerX applications (learning-guest-frontend and learning-subscription-frontend for you LinkedIn folks), but are unable to get it working. We're thinking it has something to do with the default behavior of [ignoring JS files](https://github.com/ember-template-lint/ember-template-lint/pull/2483/files#diff-11b3352c70fabcab37f5c8836ae8a377af62daa7907dc04f0f0a9a133a5d44d1), so we tried using `--no-ignore-pattern` (which takes forever since it lints EVERYTHING in the project) and then overriding `--ignore-pattern` by doing `yarn ember-template-lint . --ignore-pattern "**/dist/*,*/tmp/**,**/node_modules/**"`.

Are you able to get the .js embedded template linting to work in GlimmerX? If so, how?

**Comment by ventuno** [comment]
@tstewart15, @vagarii: you should be able to pass the list of patterns to ignore by passing the `--ignore-pattern` flag multiple times (notice the `'` around `**/tmp/**`):
```
ember-template-lint --config '{ "rules": { "no-debugger": "error" } }' --ignore-pattern **/dist/** --ignore-pattern **/node_modules/** --ignore-pattern '**/tmp/**' .
```

This is required because [`yargs` (the parser used by process optstrings) runs with the `greedy-arrays` flag set to `false`](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/helpers/cli.js#L148).

**Comment by tstewart15** [comment]
Thanks, will give that a shot! @ventuno Curious why only the "tmp" item has `'` around it? Or are you saying the final item `'` are because of the greedy-arrays flag?

**Comment by ventuno** [comment]
My assumption is that Bash is operating some substitution of the `**/tmp/**` glob pattern, in fact you may want to escape all inputs to `--ignore-pattern`.

**Comment by vagarii** [comment]
Hi @ventuno, I have tried --ignore-pattern but still no luck, do you have any other thoughts or it recently have some updates about linting embedded hbs?

**Comment by ventuno** [comment]
@vagarii, I'm not aware of any updates on this.

**Comment by yu-nathan** [comment]
Hey @ventuno! I've been looking into this issue and it seems like it's a problem with how the `hbs` template is parsed. In [extract-templates.js](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/extract-templates.js#L28), there are a few import paths specified for the `hbs` tag. We import `hbs` from `@glimmerx/component`, so I think that this is likely the issue.

**Comment by ventuno** [comment]
@yu-nathan I’m not aware of this way of importing templates. @rwjblue, @chriskrycho  is this something we can support?

**Comment by tstewart15** [comment]
@ventuno This is the import syntax from https://github.com/glimmerjs/glimmer-experimental

Also, rather than hard-coding the list of supported import paths and identifiers, should we make it configurable such that consumers can provide their own custom import paths?

**Comment by yu-nathan** [comment]
Hey @ventuno, @rwjblue, @chriskrycho any updates?

**Comment by tstewart15** [comment]
To fix the short-term issue, could we just add to the list of supported import paths?
https://github.com/ember-template-lint/ember-template-lint/compare/master...tstewart15:ember-template-lint:patch-1
