### ISSUE TITLE
[Rule proposal] Disallow redundant curly braces

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#2776]
```hbs
<SomeComponent @argument={{"asd"}} />
```

There is no need to wrap the string in curly braces. The same could be written as:

```hbs
<SomeComponent @argument="asd" />
```

Which improves readability and performance.

**Comment by runspired** [comment]
I am aware that https://github.com/ember-template-lint/ember-template-lint/pull/2794 has been merged, and some folks may want this, I would like to push back on this eventually becoming part of the recommended config without more investment in a mechanism for hinting to the rule [ember/no-bare-strings](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-bare-strings.md).

Currently, wrapping string literals in curlies is the only way by which to opt-out of this intl rule when needed. This is key because unfortunately that rule cannot be intelligent enough to understand when a string is used as a key or a path vs when it is used in a human legible form. The `elementAttributes` approach to this has in my experience not been a very useful one for many situations and proven much more difficult to maintain.

**Comment by bmish** [comment]
@runspired what about just using `{{! template-lint-disable no-bare-strings}}` for that situation? I'm worried about encouraging these unnecessary curly strings just as a means to workaround another rule.

**Comment by runspired** [comment]
A codebase with thousands of those would be a mess. Also very annoying to type everywhere, and applies to the whole block iirc.

**Comment by runspired** [comment]
I suspect the answer here is to change no-bare-strings to have an allowList for what doesn't need to be translated as opposed to one for what does need to be translated.

**Comment by bmish** [comment]
Definitely interest to make no-bare-strings smarter or more configurable to solve this...
