### ISSUE TITLE
File paths in printed output can be incomplete

### ISSUE THREAD

**Issue by pichfl** [ember-template-lint/ember-template-lint#462]
Right now the file paths printed by ember-template-lint are shortened. While this makes console output a little shorter, it also stops some terminals (like iTerm) from making the file paths clickable. 

It also makes it hard to discern template errors in in-repo addons as all of them simply start with `addon/` instead of their proper path.

If you point me to the right file, I'm happy to make a PR for this.

**Comment by rwjblue** [comment]
Is this a change from a prior version or has it always been this way? I don't particularly recall a PR that would have truncated the file names like that...

**Comment by rwjblue** [comment]
I think the issue here is that with ember-cli-template-lint the `lintTree` with a broccoli node, but we don't actually the original "on disk" location. Unfortunately this means that we can't really fix this bug in that context.

I'd suggest using the new (in Ember CLI 3.4.x) script that was added for `lint:hbs`, and this is going to use the `ember-template-lint` binary directly (instead of via `lintTree` through `ember-cli-template-lint`), and should therefore print the correct path information.

**Comment by pichfl** [comment]
I'm closing this as the solution you describe does the job quite well.
