### ISSUE TITLE
`linebreak-style` defaulting to on is hostile to Windows users

### ISSUE THREAD

**Issue by jrr** [ember-template-lint/ember-template-lint#490]
(filing at @rwjblue's request)

I work on a Mac, but run CI in Windows because of reasons.

I upgraded to Ember 3.4, suppressed the sea of new template lint violations, got a green build, and pushed.

The git client on the Windows build agent is configured to write CRLF.

Surprise! Template lint cares about your line endings for some reason.

Is there any value to this rule at all? Line endings seem like a mostly solved problem.

**Comment by rwjblue** [comment]
Submitted a fix for this in https://github.com/ember-template-lint/ember-template-lint/pull/498, instead of removing the rule by default I limited the default config to enforce that all line endings in a single file are consistent. I also added a `system` config option which would use whatever `os.EOL` is on the given system. Based on the details here I believe that _either_ of these changes would solve the reported issue...
