### ISSUE TITLE
Angle braket components trigger no-quoteless-attributes

### ISSUE THREAD

**Issue by lucacorti** [ember-template-lint/ember-template-lint#511]
`<MyComponent @attr=true/>`

However this is not an HTML attribute, so I guess this is a bug.

**Comment by rwjblue** [comment]
No, this is exactly the scenario we are trying to catch. In your template you will be passing the string “true” as an argument. This is almost never what you actually want (and is confusing to most people) so we created the rule to enforce quotes so that it becomes much clearer what is happening. If you want to pass a Boolean value you would do `@foo{{true}}`...

**Comment by rwjblue** [comment]
We should make sure that the docs (and actual error messages) make this clearer, sorry for the confusion.

**Comment by lucacorti** [comment]
Oh, great, I thought that was only the case for variables, not bare values.

**Comment by jkubaile** [comment]
This irritates me, too: for example passing the model to the component also triggers:
`<MyComponent @thing=model />`

**Comment by rwjblue** [comment]
IMHO, it’s a good thing, in your example @jkubaile you are passing the _string_ “model” not the current value of `{{model}}`!

**Comment by jkubaile** [comment]
After Reading the angle bracket RFC again it is more clear for me know. I thought I just have to replace {{ffo-bar foo=model}} with <FooBar @foo=model> and didnt get the part with the arguments. But maybe this is also a good hint here in the linting rule, also.
