### ISSUE TITLE
Unable to use with VIM ALE plugin and other external tools

### ISSUE THREAD

**Issue by sukima** [ember-template-lint/ember-template-lint#782]
Pull Request #607 introduced a breaking change where tools that call ember-template-lint with a temporary file are unable to lint because the glob rules filter out the file.

Example usage: `ember-template-lint /tmp/random-dir/temporary-template.hbs`

A built in tool like [ALE](https://github.com/w0rp/ale) will execute this command because it needs to lint the unsaved buffer.

Possible solutions:

1. disable the glob rules if the argument is a file
2. disable the rule if the path is absolute
3. allow a flag to disable globbing
4. allow reading for stdin **best solution**

**Comment by rwjblue** [comment]
> allow reading for stdin best solution

I think this is correct, but we do probably want to add a new argument to the CLI to give us the file name (e.g. `ember-template-lint --filename app/templates/components/foo-bar.hbs < /tmp/thing/here`). This is because _some_ of the rules do care about the file name (e.g. `no-outlets-outside-routes`).
